# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readMMcpp <- function(fname) {
    .Call(`_matrixmarket_readMMcpp`, fname)
}

readMMcpp2 <- function(fname) {
    .Call(`_matrixmarket_readMMcpp2`, fname)
}

readMMcpp3 <- function(fname) {
    .Call(`_matrixmarket_readMMcpp3`, fname)
}

readMMcpp4 <- function(fname) {
    .Call(`_matrixmarket_readMMcpp4`, fname)
}

readMMcpp5 <- function(fname) {
    .Call(`_matrixmarket_readMMcpp5`, fname)
}

